# Prepare environment for hadoop
---
- name: Install hadoop
  hosts: all
  become: yes
  vars:
    ssh_user: centos
    java_version: jdk1.7.0_79
    java_home: /usr/local/java/{{java_version}}
  tasks:
    
    - name: Uninstall openjdk
      yum: name=openjdk state=absent
    - name: make a directory for java
      file: path=/usr/local/java/ state=directory
    - name: download java
      command: 'wget --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" "http://download.oracle.com/otn-pub/java/jdk/7u79-b15/jdk-7u79-linux-x64.tar.gz"'
    